apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: theme-earth_fixed
spec:
  displayName: Earth-Fixed
  author:
    name: Anyexyz
    website: https://www.anye.xyz
  description: Halo 2.0 的 Earth 主题二次开发版本
  logo: https://www.halo.run/logo
  homepage: https://www.anye.xyz
  repo: https://github.com/halo-dev/theme-earth_fixed
  issues: https://github.com/halo-dev/theme-earth_fixed/issues
  settingName: "theme-earth_fixed-setting"
  configMapName: "theme-earth_fixed-configMap"
  version: 1.11.0
  requires: ">=2.20.0"
  license:
    - name: "GPL-3.0"
      url: "https://github.com/Anyexyz/theme-earth_fixed/blob/main/LICENSE"
  customTemplates:
    page:
      - name: 友链
        description: 友链页面，包含评论
        screenshot:
        file: friends.html
